### ISSUE TITLE
AttributeError: Can only use .cat accessor with a 'category' dtype

### ISSUE THREAD

**Issue by MichaelPeibo** [amisios/Planaria_lineage#2]
Hi, PAGA team

I came to an error when I run
`adata.obs['clusters'].cat.reorder_categories`

I have 18 cluster in my Seurat categories, when I export annotation file in txt, and run like this
`clusters = pd.read_csv('/Users/peiboxu/Desktop/PAGA/mda.anno.txt',header=None)`
`adata.obs['clusters'] = clusters[0].values
adata.uns['iroot'] = 6  # root cell (the first neoblast in the file)`
`sc.utils.sanitize_anndata(adata)`
```
adata.obs['clusters'].cat.reorder_categories([
    'early epidermal progenitors', 'activated early epidermal progenitors',
    'epidermal neoblasts', 'epidermis', 'epidermis DVb',
    'epidermis DVb neoblast', 'glia', 'phagocytes', 'goblet cells',
    'psd+ cells', 'gut progenitors', 'late epidermal progenitors 1',
    'late epidermal progenitors 2', 'muscle body', 'muscle pharynx',
    'muscle progenitors', 'neoblast 1'], inplace=True)
```
I got this error

> AttributeError                            Traceback (most recent call last)
<ipython-input-41-40377e82b6ad> in <module>()
----> 1 adata.obs['clusters'].cat.reorder_categories([
      2     'early epidermal progenitors', 'activated early epidermal progenitors',
      3     'epidermal neoblasts', 'epidermis', 'epidermis DVb',
      4     'epidermis DVb neoblast', 'glia', 'phagocytes', 'goblet cells',
      5     'psd+ cells', 'gut progenitors', 'late epidermal progenitors 1',

> ~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
>    4370         if (name in self._internal_names_set or name in self._metadata or
>    4371                 name in self._accessors):
> -> 4372             return object.__getattribute__(self, name)
>    4373         else:
>    4374             if self._info_axis._can_hold_identifiers_and_holds_name(name):
> 
> ~/anaconda3/lib/python3.6/site-packages/pandas/core/accessor.py in __get__(self, obj, cls)
>     131             # we're accessing the attribute of the class, i.e., Dataset.geo
>     132             return self._accessor
> --> 133         accessor_obj = self._accessor(obj)
>     134         # Replace the property with the accessor object. Inspired by:
>     135         # http://www.pydanny.com/cached-property.html
> 
> ~/anaconda3/lib/python3.6/site-packages/pandas/core/arrays/categorical.py in __init__(self, data)
>    2375 
>    2376     def __init__(self, data):
> -> 2377         self._validate(data)
>    2378         self.categorical = data.values
>    2379         self.index = data.index
> 
> ~/anaconda3/lib/python3.6/site-packages/pandas/core/arrays/categorical.py in _validate(data)
>    2384     def _validate(data):
>    2385         if not is_categorical_dtype(data.dtype):
> -> 2386             raise AttributeError("Can only use .cat accessor with a "
>    2387                                  "'category' dtype")
>    2388 
> 
> AttributeError: Can only use .cat accessor with a 'category' dtype
> 

When I compare the annotation file, as `clusters`, I found dtype in tutorial is `object`, but I got dtype as `int64`,so i tried to convert my data into object type by 
`clusters[0].apply(str)`
but I still got this error when I run `adata.obs['clusters'].cat.reorder_categories`

Any suggestions? I doubt I have not fully understand the data type used in your case and how you export your annotation file from Seurat.

**Comment by falexwolf** [comment]
Hi! 

Your dtype needs to be `category`, neither `str` or `int`. You can simply call `.astype('category')`.

Please submit issues for PAGA on https://github.com/theislab/paga, where you'll also find more recent tutorials.

**Comment by MichaelPeibo** [comment]
Hi, 
thanks for help.

1. I went through this using `adata.obs['clusters'] = clusters[0].astype('category').values` as you suggested.

2. When I tried to run 

> Cell map from PAGA part

 I got an `keyerror` for `confidence_tree` and `confidence`, which is predetermined in tutorial and I have no idea how should I manage them? or is there any documentation for some explanation?

Thanks in advance!

PLUS, I got same error by repeating [this turorial](https://nbviewer.jupyter.org/github/rajewsky-lab/planarian_lineages/blob/master/paga/planaria.ipynb#Planarian-lineages:-cell-map-from-PAGA)

**Comment by falexwolf** [comment]
All the documentation is on https://scanpy.readthedocs.io and is linked from  https://github.com/theislab/paga. Are you sure you're running the latest release of Scanpy? At least 1.2?

You're error indicates that something super fundamental is going wrong.

You can check what your AnnData contains by print it
```
print(adata)
```
or by printing the contents of an element
```
print(adata.uns['paga']
```

**Comment by MichaelPeibo** [comment]
Hi, Alex

You are right, I am using old codes from [here](https://nbviewer.jupyter.org/github/rajewsky-lab/planarian_lineages/blob/master/paga/planaria.ipynb#Planarian-lineages:-cell-map-from-PAGA)
when I try new one from https://github.com/theislab/paga, it worked.

Thanks for helping, if I have other questions, I will address a new issue in https://github.com/theislab/paga
